apiVersion: v1
kind: Service
metadata:
  name: php-nginx
spec:
  selector:
    app: php
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerIP: 127.0.0.1
